AWSTemplateFormatVersion: 2010-09-09
Parameters:
  GithubRepo:
    Type: "String"
    Default: "serverless-api"
  GithubUser:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /training/serverless/user
  GithubToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /training/serverless/token
  GithubBranch:
    Type: AWS::SSM::Parameter::Value<String>
    Default:/training/serverless/branch

Resources:
  #    ____  ___   ____   _____  ____  ___  ____   _____  _      ___  _   _  _____     __        __ _____  ____   _   _   ___    ___   _  __
  #   / ___|/ _ \ |  _ \ | ____||  _ \|_ _||  _ \ | ____|| |    |_ _|| \ | || ____|    \ \      / /| ____|| __ ) | | | | / _ \  / _ \ | |/ /
  #  | |   | | | || | | ||  _|  | |_) || | | |_) ||  _|  | |     | | |  \| ||  _|  _____\ \ /\ / / |  _|  |  _ \ | |_| || | | || | | || ' /
  #  | |___| |_| || |_| || |___ |  __/ | | |  __/ | |___ | |___  | | | |\  || |___|_____|\ V  V /  | |___ | |_) ||  _  || |_| || |_| || . \
  #   \____|\___/ |____/ |_____||_|   |___||_|    |_____||_____||___||_| \_||_____|       \_/\_/   |_____||____/ |_| |_| \___/  \___/ |_|\_\

  CodePipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GithubToken
      Filters:
        - JsonPath: "$.ref"
          MatchEquals: !Sub "refs/heads/${GithubBranch}"
      TargetPipeline: !Ref CodePipeline
      TargetAction: Source
      Name: !Sub "${GithubRepo}-webhook"
      TargetPipelineVersion: !GetAtt CodePipeline.Version
      RegisterWithThirdParty: true

  #   ____   _    _  _____  _       _____
  #  |  _ \ | |  | ||_   _|| |     |  __ \
  #  | |_) || |  | |  | |  | |     | |  | |
  #  |  _ < | |  | |  | |  | |     | |  | |
  #  | |_) || |__| | _| |_ | |____ | |__| |
  #  |____/  \____/ |_____||______||_____/

  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref GithubRepo
      Description: !Sub "Build project for ${GithubRepo}"
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      ServiceRole: "arn:aws:iam::795124088981:role/codebuild-role"
      Source:
        Type: CODEPIPELINE
        BuildSpec: "buildspec.yaml"

  #   _____  _____  _____   ______  _       _____  _   _  ______
  #  |  __ \|_   _||  __ \ |  ____|| |     |_   _|| \ | ||  ____|
  #  | |__) | | |  | |__) || |__   | |       | |  |  \| || |__
  #  |  ___/  | |  |  ___/ |  __|  | |       | |  | . ` ||  __|
  #  | |     _| |_ | |     | |____ | |____  _| |_ | |\  || |____
  #  |_|    |_____||_|     |______||______||_____||_| \_||______|

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: training-codepipeline-artifacts
        Type: S3
      Name: !Ref GithubRepo
      RoleArn: "arn:aws:iam::795124088981:role/codepipeline-role"
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              Configuration:
                Owner: !Ref GithubUser
                Repo: !Ref GithubRepo
                Branch: !Ref GithubBranch
                OAuthToken: !Ref GithubToken
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: SourceCodeAsZip
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuild
              InputArtifacts:
                - Name: SourceCodeAsZip
              OutputArtifacts:
                - Name: BuildArtifactAsZip
        - Name: Deploy
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: "arn:aws:iam::795124088981:role/cloudformation-role"
                StackName: !Ref GithubRepo
                ChangeSetName: !Sub "${GithubRepo}-changeset"
                TemplatePath: BuildArtifactAsZip::packaged.yaml
                Capabilities: CAPABILITY_IAM
              InputArtifacts:
                - Name: BuildArtifactAsZip
              RunOrder: 1
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                RoleArn: "arn:aws:iam::795124088981:role/cloudformation-role"
                StackName: !Ref GithubRepo
                ChangeSetName: !Sub "${GithubRepo}-changeset"
              OutputArtifacts:
                - Name: !Sub "${GithubRepo}-deployment-changeset"
              RunOrder: 2

#    ____   _    _  _______  _____   _    _  _______  _____
#   / __ \ | |  | ||__   __||  __ \ | |  | ||__   __|/ ____|
#  | |  | || |  | |   | |   | |__) || |  | |   | |  | (___
#  | |  | || |  | |   | |   |  ___/ | |  | |   | |   \___ \
#  | |__| || |__| |   | |   | |     | |__| |   | |   ____) |
#   \____/  \____/    |_|   |_|      \____/    |_|  |_____/

Outputs:
  CodeBuild:
    Description: CodeBuild Project name
    Value: !Ref CodeBuild

  CodePipeline:
    Description: AWS CodePipeline pipeline name
    Value: !Ref CodePipeline
